### ISSUE TITLE
vetur v0.6.1  Vue文件自动格式化失效

### ISSUE THREAD

**Issue by Chreem** [Chreem/chreem-site#20]
vetur的issue下有部分码友提出v0.6.0出现server crash, 于是乎作者大大今天中午赶紧发出了v0.6.1来修复...  
然而我更新后依然出错  ~就是所谓的脸黑么T^T~  
```log
C:\Users\XXX\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (C:\Users\XXX\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:10566:19)
    at Object.createTextSpanFromBounds (C:\Users\XXX\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:10575:16)
    at getErrorSpanForNode (C:\Users\XXX\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (C:\Users\XXX\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:6999:20)
    at Object.createDiagnosticForNode (C:\Users\XXXX\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:6995:16)
    at C:\Users\XXX\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:21582:58
    at Object.forEach (C:\Users\XXX\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:1423:30)
    at declareSymbol (C:\Users\XXX\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:21581:28)
    at declareModuleMember (C:\Users\XXX\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:21600:28)
    at declareSourceFileMember (C:\Users\XXX\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:22646:19)
[Info  - 下午2:13:17] Connection to server got closed. Server will restart.
```

**Comment by Chreem** [comment]
在[这个issue下的comment](https://github.com/octref/vetur/issues/128#issuecomment-296069915)帮助下解决了  
原因是为了将element-ui引用范围限制在code页而在code.vue下[引用Vue(大写V)](https://github.com/Chreem/chreem-site/blob/master/src/views/code/code.vue#L36)导致  
改成小写正常使用  

```html
<script>
import vue from 'vue';
import ElementUI from 'element-ui';
vue.use(ElementUI);
...
</script>
```

**Comment by Chreem** [comment]
更新到0.9.11后又出现了类似问题 提示can't find module lodash  
详情<https://github.com/vuejs/vetur/issues/352#issuecomment-318226753>  
进入插件目录yarn install即可
